# Generated by Django 4.0.10 on 2023-10-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
